from .sw_h3_segments import (
    NODE_CLASS_MAPPINGS as _SEG_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _SEG_NAMES,
)
from .sw_h3_multiprompt import (
    NODE_CLASS_MAPPINGS as _MULTI_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _MULTI_NAMES,
)

from .sw_h3_ultra import (
    NODE_CLASS_MAPPINGS as _ULTRA_CLASS,
    NODE_DISPLAY_NAME_MAPPINGS as _ULTRA_NAMES,
)

NODE_CLASS_MAPPINGS = {**_SEG_CLASS, **_MULTI_CLASS, **_ULTRA_CLASS}
NODE_DISPLAY_NAME_MAPPINGS = {**_SEG_NAMES, **_MULTI_NAMES, **_ULTRA_NAMES}

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
